### ISSUE TITLE
Allowing fn.op operations to take more than two args

### ISSUE THREAD

**Issue by dillonforrest** [CrowdHailer/fn.js#16]
I'm envisioning something along the lines of:

```javascript
expect( fn.op['+'](1, 2, 3, 4, 5) ).to.equal(15);
expect( fn.op['-'](8, 4, 1) ).to.equal(3);
```

The implementation would simply be reducing all the `arguments`.

I also feel that `fn.op['>']` and `fn.op['<']` would be incredibly useful see if a series of numbers are ascending or descending:

```javascript
expect( fn.op['<'](1, 2) ).to.be.true;

// descending
var testScores = [88, 77, 66, 55]
expect ( fn.apply( fn.op['>'], testScores ) ).to.be.true;
```

I'd implement `fn.op['>']` and `fn.op['<']` with simple recursion.

What are your thoughts?

**Comment by CrowdHailer** [comment]
@dillonforrest Anything become of this suggestion?

**Comment by dillonforrest** [comment]
@CrowdHailer nope!
